### PR TITLE
REST samples for vCSA appliance

### PR DESCRIPTION
**Pull request by lrivallain**
Signed-off-by: Ludovic Rivallain <ludovic.rivallain@gmail.com>

### CODE REVIEW

**Comment by lrivallain** [comment]
Hi @vmwclabot. It's already done from my point of view, isn't it?

**Comment by travisfinch** [comment]
Format must be:

Signed-off-by: Ludovic Rivallain <ludovic.rivallain@gmail.com>

**Comment by travisfinch** [comment]
The format must be:

`Signed-off-by: Ludovic Rivallain <ludovic.rivallain@gmail.com>`

**Comment by lrivallain** [comment]
Ok fixed. I've missed the diple symbole "</>" in the email.

**Comment by alanrenouf** [comment]
Fantastic work, love this! works perfectly for me.

**Comment by alanrenouf** [comment]
Tested and approved

**Pull request merged**
